resolver 127.0.0.11 valid=5s ipv6=off;

server {
    listen 80;
    server_name terrashare.duckdns.org success.terrashare.duckdns.org
                 terrashare-test.duckdns.org success.terrashare-test.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name terrashare.duckdns.org success.terrashare.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/terrashare.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/terrashare.duckdns.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    set $prod_web terrashare-prod-web-1;
    set $prod_api terrashare-prod-backend-api-1;

    location / {
        proxy_pass http://$prod_web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://$prod_api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name terrashare-test.duckdns.org success.terrashare-test.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/terrashare-test.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/terrashare-test.duckdns.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    set $staging_web terrashare-staging-web-1;
    set $staging_api terrashare-staging-backend-api-1;

    location / {
        proxy_pass http://$staging_web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
        proxy_pass http://$staging_api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
